var letters = [
  {"character": "\u{1200}", "letter": "ሀ", "form": "1"},
  {"character": "\u{1201}", "letter": "ሁ", "form": "2"},
  {"character": "\u{1202}", "letter": "ሂ", "form": "3"},
  {"character": "\u{1203}", "letter": "ሃ", "form": "4"},
  {"character": "\u{1204}", "letter": "ሄ", "form": "5"},
  {"character": "\u{1205}", "letter": "ህ", "form": "6"},
  {"character": "\u{1206}", "letter": "ሆ", "form": "7"},
  {"character": "\u{1208}", "letter": "ለ", "form": "1"},
  {"character": "\u{1209}", "letter": "ሉ", "form": "2"},
  {"character": "\u{120a}", "letter": "ሊ", "form": "3"},
  {"character": "\u{120b}", "letter": "ላ", "form": "4"},
  {"character": "\u{120c}", "letter": "ሌ", "form": "5"},
  {"character": "\u{120d}", "letter": "ል", "form": "6"},
  {"character": "\u{120e}", "letter": "ሎ", "form": "7"},
  {"character": "\u{1210}", "letter": "ሐ", "form": "1"},
  {"character": "\u{1211}", "letter": "ሑ", "form": "2"},
  {"character": "\u{1212}", "letter": "ሒ", "form": "3"},
  {"character": "\u{1213}", "letter": "ሓ", "form": "4"},
  {"character": "\u{1214}", "letter": "ሔ", "form": "5"},
  {"character": "\u{1215}", "letter": "ሕ", "form": "6"},
  {"character": "\u{1216}", "letter": "ሖ", "form": "7"},
  {"character": "\u{1218}", "letter": "መ", "form": "1"},
  {"character": "\u{1219}", "letter": "ሙ", "form": "2"},
  {"character": "\u{121a}", "letter": "ሚ", "form": "3"},
  {"character": "\u{121b}", "letter": "ማ", "form": "4"},
  {"character": "\u{121c}", "letter": "ሜ", "form": "5"},
  {"character": "\u{121d}", "letter": "ም", "form": "6"},
  {"character": "\u{121e}", "letter": "ሞ", "form": "7"},
  {"character": "\u{1220}", "letter": "ሠ", "form": "1"},
  {"character": "\u{1221}", "letter": "ሡ", "form": "2"},
  {"character": "\u{1222}", "letter": "ሢ", "form": "3"},
  {"character": "\u{1223}", "letter": "ሣ", "form": "4"},
  {"character": "\u{1224}", "letter": "ሤ", "form": "5"},
  {"character": "\u{1225}", "letter": "ሥ", "form": "6"},
  {"character": "\u{1226}", "letter": "ሦ", "form": "7"},
  {"character": "\u{1228}", "letter": "ረ", "form": "1"},
  {"character": "\u{1229}", "letter": "ሩ", "form": "2"},
  {"character": "\u{122a}", "letter": "ሪ", "form": "3"},
  {"character": "\u{122b}", "letter": "ራ", "form": "4"},
  {"character": "\u{122c}", "letter": "ሬ", "form": "5"},
  {"character": "\u{122d}", "letter": "ር", "form": "6"},
  {"character": "\u{122e}", "letter": "ሮ", "form": "7"},
  {"character": "\u{1230}", "letter": "ሰ", "form": "1"},
  {"character": "\u{1231}", "letter": "ሱ", "form": "2"},
  {"character": "\u{1232}", "letter": "ሲ", "form": "3"},
  {"character": "\u{1233}", "letter": "ሳ", "form": "4"},
  {"character": "\u{1234}", "letter": "ሴ", "form": "5"},
  {"character": "\u{1235}", "letter": "ስ", "form": "6"},
  {"character": "\u{1236}", "letter": "ሶ", "form": "7"},
  {"character": "\u{1238}", "letter": "ሸ", "form": "1"},
  {"character": "\u{1239}", "letter": "ሹ", "form": "2"},
  {"character": "\u{123a}", "letter": "ሺ", "form": "3"},
  {"character": "\u{123b}", "letter": "ሻ", "form": "4"},
  {"character": "\u{123c}", "letter": "ሼ", "form": "5"},
  {"character": "\u{123d}", "letter": "ሽ", "form": "6"},
  {"character": "\u{123e}", "letter": "ሾ", "form": "7"},
  {"character": "\u{1240}", "letter": "ቀ", "form": "1"},
  {"character": "\u{1241}", "letter": "ቁ", "form": "2"},
  {"character": "\u{1242}", "letter": "ቂ", "form": "3"},
  {"character": "\u{1243}", "letter": "ቃ", "form": "4"},
  {"character": "\u{1244}", "letter": "ቄ", "form": "5"},
  {"character": "\u{1245}", "letter": "ቅ", "form": "6"},
  {"character": "\u{1246}", "letter": "ቆ", "form": "7"},
  {"character": "\u{1260}", "letter": "በ", "form": "1"},
  {"character": "\u{1261}", "letter": "ቡ", "form": "2"},
  {"character": "\u{1262}", "letter": "ቢ", "form": "3"},
  {"character": "\u{1263}", "letter": "ባ", "form": "4"},
  {"character": "\u{1264}", "letter": "ቤ", "form": "5"},
  {"character": "\u{1265}", "letter": "ብ", "form": "6"},
  {"character": "\u{1266}", "letter": "ቦ", "form": "7"},
  {"character": "\u{1270}", "letter": "ተ", "form": "1"},
  {"character": "\u{1271}", "letter": "ቱ", "form": "2"},
  {"character": "\u{1272}", "letter": "ቲ", "form": "3"},
  {"character": "\u{1273}", "letter": "ታ", "form": "4"},
  {"character": "\u{1274}", "letter": "ቴ", "form": "5"},
  {"character": "\u{1275}", "letter": "ት", "form": "6"},
  {"character": "\u{1276}", "letter": "ቶ", "form": "7"},
  {"character": "\u{1278}", "letter": "ቸ", "form": "1"},
  {"character": "\u{1279}", "letter": "ቹ", "form": "2"},
  {"character": "\u{127a}", "letter": "ቺ", "form": "3"},
  {"character": "\u{127b}", "letter": "ቻ", "form": "4"},
  {"character": "\u{127c}", "letter": "ቼ", "form": "5"},
  {"character": "\u{127d}", "letter": "ች", "form": "6"},
  {"character": "\u{127e}", "letter": "ቾ", "form": "7"},
  {"character": "\u{1280}", "letter": "ኀ", "form": "1"},
  {"character": "\u{1281}", "letter": "ኁ", "form": "2"},
  {"character": "\u{1282}", "letter": "ኂ", "form": "3"},
  {"character": "\u{1283}", "letter": "ኃ", "form": "4"},
  {"character": "\u{1284}", "letter": "ኄ", "form": "5"},
  {"character": "\u{1285}", "letter": "ኅ", "form": "6"},
  {"character": "\u{1286}", "letter": "ኆ", "form": "7"},
  {"character": "\u{1290}", "letter": "ነ", "form": "1"},
  {"character": "\u{1291}", "letter": "ኑ", "form": "2"},
  {"character": "\u{1292}", "letter": "ኒ", "form": "3"},
  {"character": "\u{1293}", "letter": "ና", "form": "4"},
  {"character": "\u{1294}", "letter": "ኔ", "form": "5"},
  {"character": "\u{1295}", "letter": "ን", "form": "6"},
  {"character": "\u{1296}", "letter": "ኖ", "form": "7"},
  {"character": "\u{1298}", "letter": "ኘ", "form": "1"},
  {"character": "\u{1299}", "letter": "ኙ", "form": "2"},
  {"character": "\u{129a}", "letter": "ኚ", "form": "3"},
  {"character": "\u{129b}", "letter": "ኛ", "form": "4"},
  {"character": "\u{129c}", "letter": "ኜ", "form": "5"},
  {"character": "\u{129d}", "letter": "ኝ", "form": "6"},
  {"character": "\u{129e}", "letter": "ኞ", "form": "7"},
  {"character": "\u{12a0}", "letter": "አ", "form": "1"},
  {"character": "\u{12a1}", "letter": "ኡ", "form": "2"},
  {"character": "\u{12a2}", "letter": "ኢ", "form": "3"},
  {"character": "\u{12a3}", "letter": "ኣ", "form": "4"},
  {"character": "\u{12a4}", "letter": "ኤ", "form": "5"},
  {"character": "\u{12a5}", "letter": "እ", "form": "6"},
  {"character": "\u{12a6}", "letter": "ኦ", "form": "7"},
  {"character": "\u{12a8}", "letter": "ከ", "form": "1"},
  {"character": "\u{12a9}", "letter": "ኩ", "form": "2"},
  {"character": "\u{12aa}", "letter": "ኪ", "form": "3"},
  {"character": "\u{12ab}", "letter": "ካ", "form": "4"},
  {"character": "\u{12ac}", "letter": "ኬ", "form": "5"},
  {"character": "\u{12ad}", "letter": "ክ", "form": "6"},
  {"character": "\u{12ae}", "letter": "ኮ", "form": "7"},
  {"character": "\u{12b8}", "letter": "ኸ", "form": "1"},
  {"character": "\u{12b9}", "letter": "ኹ", "form": "2"},
  {"character": "\u{12ba}", "letter": "ኺ", "form": "3"},
  {"character": "\u{12bb}", "letter": "ኻ", "form": "4"},
  {"character": "\u{12bc}", "letter": "ኼ", "form": "5"},
  {"character": "\u{12bd}", "letter": "ኽ", "form": "6"},
  {"character": "\u{12be}", "letter": "ኾ", "form": "7"},
  {"character": "\u{12c0}", "letter": "ዀ", "form": "1"},
  {"character": "\u{12c8}", "letter": "ወ", "form": "1"},
  {"character": "\u{12c9}", "letter": "ዉ", "form": "2"},
  {"character": "\u{12ca}", "letter": "ዊ", "form": "3"},
  {"character": "\u{12cb}", "letter": "ዋ", "form": "4"},
  {"character": "\u{12cc}", "letter": "ዌ", "form": "5"},
  {"character": "\u{12cd}", "letter": "ው", "form": "6"},
  {"character": "\u{12ce}", "letter": "ዎ", "form": "7"},
  {"character": "\u{12d0}", "letter": "ዐ", "form": "1"},
  {"character": "\u{12d1}", "letter": "ዑ", "form": "2"},
  {"character": "\u{12d2}", "letter": "ዒ", "form": "3"},
  {"character": "\u{12d3}", "letter": "ዓ", "form": "4"},
  {"character": "\u{12d4}", "letter": "ዔ", "form": "5"},
  {"character": "\u{12d5}", "letter": "ዕ", "form": "6"},
  {"character": "\u{12d6}", "letter": "ዖ", "form": "7"},
  {"character": "\u{12d8}", "letter": "ዘ", "form": "1"},
  {"character": "\u{12d9}", "letter": "ዙ", "form": "2"},
  {"character": "\u{12da}", "letter": "ዚ", "form": "3"},
  {"character": "\u{12db}", "letter": "ዛ", "form": "4"},
  {"character": "\u{12dc}", "letter": "ዜ", "form": "5"},
  {"character": "\u{12dd}", "letter": "ዝ", "form": "6"},
  {"character": "\u{12de}", "letter": "ዞ", "form": "7"},
  {"character": "\u{12e0}", "letter": "ዠ", "form": "1"},
  {"character": "\u{12e1}", "letter": "ዡ", "form": "2"},
  {"character": "\u{12e2}", "letter": "ዢ", "form": "3"},
  {"character": "\u{12e3}", "letter": "ዣ", "form": "4"},
  {"character": "\u{12e4}", "letter": "ዤ", "form": "5"},
  {"character": "\u{12e5}", "letter": "ዥ", "form": "6"},
  {"character": "\u{12e6}", "letter": "ዦ", "form": "7"},
  {"character": "\u{12e8}", "letter": "የ", "form": "1"},
  {"character": "\u{12e9}", "letter": "ዩ", "form": "2"},
  {"character": "\u{12ea}", "letter": "ዪ", "form": "3"},
  {"character": "\u{12eb}", "letter": "ያ", "form": "4"},
  {"character": "\u{12ec}", "letter": "ዬ", "form": "5"},
  {"character": "\u{12ed}", "letter": "ይ", "form": "6"},
  {"character": "\u{12ee}", "letter": "ዮ", "form": "7"},
  {"character": "\u{12f0}", "letter": "ደ", "form": "1"},
  {"character": "\u{12f1}", "letter": "ዱ", "form": "2"},
  {"character": "\u{12f2}", "letter": "ዲ", "form": "3"},
  {"character": "\u{12f3}", "letter": "ዳ", "form": "4"},
  {"character": "\u{12f4}", "letter": "ዴ", "form": "5"},
  {"character": "\u{12f5}", "letter": "ድ", "form": "6"},
  {"character": "\u{12f6}", "letter": "ዶ", "form": "7"},
  {"character": "\u{1300}", "letter": "ጀ", "form": "1"},
  {"character": "\u{1301}", "letter": "ጁ", "form": "2"},
  {"character": "\u{1302}", "letter": "ጂ", "form": "3"},
  {"character": "\u{1303}", "letter": "ጃ", "form": "4"},
  {"character": "\u{1304}", "letter": "ጄ", "form": "5"},
  {"character": "\u{1305}", "letter": "ጅ", "form": "6"},
  {"character": "\u{1306}", "letter": "ጆ", "form": "7"},
  {"character": "\u{1308}", "letter": "ገ", "form": "1"},
  {"character": "\u{1309}", "letter": "ጉ", "form": "2"},
  {"character": "\u{130a}", "letter": "ጊ", "form": "3"},
  {"character": "\u{130b}", "letter": "ጋ", "form": "4"},
  {"character": "\u{130c}", "letter": "ጌ", "form": "5"},
  {"character": "\u{130d}", "letter": "ግ", "form": "6"},
  {"character": "\u{130e}", "letter": "ጎ", "form": "7"},
  {"character": "\u{1320}", "letter": "ጠ", "form": "1"},
  {"character": "\u{1321}", "letter": "ጡ", "form": "2"},
  {"character": "\u{1322}", "letter": "ጢ", "form": "3"},
  {"character": "\u{1323}", "letter": "ጣ", "form": "4"},
  {"character": "\u{1324}", "letter": "ጤ", "form": "5"},
  {"character": "\u{1325}", "letter": "ጥ", "form": "6"},
  {"character": "\u{1326}", "letter": "ጦ", "form": "7"},
  {"character": "\u{1328}", "letter": "ጨ", "form": "1"},
  {"character": "\u{1329}", "letter": "ጩ", "form": "2"},
  {"character": "\u{132a}", "letter": "ጪ", "form": "3"},
  {"character": "\u{132b}", "letter": "ጫ", "form": "4"},
  {"character": "\u{132c}", "letter": "ጬ", "form": "5"},
  {"character": "\u{132d}", "letter": "ጭ", "form": "6"},
  {"character": "\u{132e}", "letter": "ጮ", "form": "7"},
  {"character": "\u{1330}", "letter": "ጰ", "form": "1"},
  {"character": "\u{1331}", "letter": "ጱ", "form": "2"},
  {"character": "\u{1332}", "letter": "ጲ", "form": "3"},
  {"character": "\u{1333}", "letter": "ጳ", "form": "4"},
  {"character": "\u{1334}", "letter": "ጴ", "form": "5"},
  {"character": "\u{1335}", "letter": "ጵ", "form": "6"},
  {"character": "\u{1336}", "letter": "ጶ", "form": "7"},
  {"character": "\u{1338}", "letter": "ጸ", "form": "1"},
  {"character": "\u{1339}", "letter": "ጹ", "form": "2"},
  {"character": "\u{133a}", "letter": "ጺ", "form": "3"},
  {"character": "\u{133b}", "letter": "ጻ", "form": "4"},
  {"character": "\u{133c}", "letter": "ጼ", "form": "5"},
  {"character": "\u{133d}", "letter": "ጽ", "form": "6"},
  {"character": "\u{133e}", "letter": "ጾ", "form": "7"},
  {"character": "\u{1340}", "letter": "ፀ", "form": "1"},
  {"character": "\u{1341}", "letter": "ፁ", "form": "2"},
  {"character": "\u{1342}", "letter": "ፂ", "form": "3"},
  {"character": "\u{1343}", "letter": "ፃ", "form": "4"},
  {"character": "\u{1344}", "letter": "ፄ", "form": "5"},
  {"character": "\u{1345}", "letter": "ፅ", "form": "6"},
  {"character": "\u{1346}", "letter": "ፆ", "form": "7"},
  {"character": "\u{1348}", "letter": "ፈ", "form": "1"},
  {"character": "\u{1349}", "letter": "ፉ", "form": "2"},
  {"character": "\u{134a}", "letter": "ፊ", "form": "3"},
  {"character": "\u{134b}", "letter": "ፋ", "form": "4"},
  {"character": "\u{134c}", "letter": "ፌ", "form": "5"},
  {"character": "\u{134d}", "letter": "ፍ", "form": "6"},
  {"character": "\u{134e}", "letter": "ፎ", "form": "7"},
  {"character": "\u{1350}", "letter": "ፐ", "form": "1"},
  {"character": "\u{1351}", "letter": "ፑ", "form": "2"},
  {"character": "\u{1352}", "letter": "ፒ", "form": "3"},
  {"character": "\u{1353}", "letter": "ፓ", "form": "4"},
  {"character": "\u{1354}", "letter": "ፔ", "form": "5"},
  {"character": "\u{1355}", "letter": "ፕ", "form": "6"},
  {"character": "\u{1356}", "letter": "ፖ", "form": "7"}
];
var hints = [
  {"ሀሁሂሃሄህሆ": "ha.PNG"},
  {"ለሉሊላሌልሎ": "leh.PNG"},
  {"ሐሑሒሓሔሕሖ": "hah.PNG"},
  {"መሙሚማሜምሞ": "meh.PNG"},
  {"ሠሡሢሣሤሥሦ": "seh.PNG"},
  {"ረሩሪራሬርሮ": "re.PNG"},
  {"ሰሱሲሳሴስሶ": "seh2.PNG"},
  {"ሸሹሺሻሼሽሾ": "she.PNG"},
  {"ቀቁቂቃቄቅቆ": "ke.PNG"},
  {"በቡቢባቤብቦ": "be.PNG"},
  {"ተቱቲታቴትቶ": "te.PNG"},
  {"ቸቹቺቻቼችቾ": "che.PNG"},
  {"ኀኁኂኃኄኅኆ": "ha1.PNG"},
  {"ነኑኒናኔንኖ": "ne.PNG"},
  {"ኘኙኚኛኜኝኞ": "gne.PNG"},
  {"አኡኢኣኤእኦ": "ah.PNG"},
  {"ከኩኪካኬክኮ": "keh.PNG"},
  {"ወዉዊዋዌውዎ": "weh.PNG"},
  {"ዐዑዒዓዔዕዖ": "ah1.PNG"},
  {"ዘዙዚዛዜዝዞ": "ze.PNG"},
  {"ዠዡዢዣዤዥዦ": "zhe.PNG"},
  {"የዩዪያዬይዮ": "ye.PNG"},
  {"ደዱዲዳዴድዶ": "de.PNG"},
  {"ጀጁጂጃጄጅጆ": "je.PNG"},
  {"ገጉጊጋጌግጎ": "ge.PNG"},
  {"ጠጡጢጣጤጥጦ": "teh.PNG"},
  {"ጨጩጪጫጬጭጮ": "cheh.PNG"},
  {"ጰጱጲጳጴጵጶ": "peh.PNG"},
  {"ጸጹጺጻጼጽጾ": "tseh.PNG"},
  {"ፀፁፂፃፄፅፆ": "tseh1.PNG"},
  {"ፈፉፊፋፌፍፎ": "feh.PNG"},
  {"ፐፑፒፓፔፕፖ": "pehh.PNG"}
];
